### ISSUE TITLE
Enddatum für Regelungen

### ISSUE THREAD

**Issue by Syphdias** [v-braun/corona-wiki#29]
Die Beschlüsse der MPK sind in der Regel begrenzt auf einen Zweitraum – z.B. bis zur nächten MPK.

Es kann zwar sein, dass hier Regeln verlängert werden, muss aber nicht sein. Aktuell ist `date_to` nur für Schulen in NI gesetzt.

**Comment by v-braun** [comment]
Ich bin mir gerade nicht sicher warum ich es bei Schulen gesetz hab.
Eigentlich gehe ich folgendermaßen vor:
gibt es eine aktuelle Regel ohne der Aussage dass es später eine Regeländerung gibt, dann setze ich keine Laufzeit.

Gibt es eine aktuelle Regel ABER das BL hat schon angekündigt dass es in 1 oder 2 Wochen weitere Lockerungen gibt, dann setze ich an der aktuellen Regel ein `date_to` und an die zukünftige Regel ein `date_from`

**Comment by Syphdias** [comment]
> 3. Die bestehenden Beschlüsse der Bundeskanzlerin und der Regierungschefinnen
und Regierungschefs der Länder bleiben weiterhin gültig, sofern dieser Beschluss
keine abweichenden Festlegungen trifft. Die Länder werden ihre
Landesverordnungen entsprechend anpassen und bis zum 28. März 2021
verlängern.

Vielleicht lese ich das falsch, aber klingt für mich nach: "Ab 28. März laufen die Maßnahmen aus dem Beschluss vom 3. März aus." Das pasiert natürlich nicht, weil ab 22. März die nächste Ministerpräsidentenkonferenz ist, wo im Beschluss dann drin stehen könnte, dass es verlängert/angepasst/erweitert wird.

**Comment by v-braun** [comment]
Genau so ist es.


Es gibt ja zwei Fälle die eintreten können:
Am 22.3 wird kaum was geändert (ein paar mehr Öffnungen aber im großen und ganzen bleibt alles gleich):
Man müsste nun durch alle Regeln durch und das Ablaufdatum anpassen
*oder* nichts tun, dabei aber riskieren dass einige Regeln falsch sind da diese am 22.3 geändert wurden.

Am 22.3 wird richtig viel geändert:
Hat man ein Ablaufdatum: das ganze Wiki wird warscheinlich komplett leer sein.
Hat man **kein** Ablaufdatum: das Wiki wird defnitiv falsche Infos anzeigen.


Aktuell denke ich dass es wirklich vom Fall zu Fall abhängig ist.
Pauschal zu sagen **alle** Regeln bekommen ein Ablaufdatum ist falsch.
Lebensmittelgeschäfte/Apotheken/etc. bleiben offen.
Schulen könnten für bestimmte Jahrgänge wieder schließen.
In der Mitte liegen die Friseure -- da muss man selbst abwegen wie Warscheinlich ist eine Regeländerung.


Daher tu ich mich wirklich schwer dem Gesetzestext zu folgen und überall den 28.3 zu setzen.

**Comment by Syphdias** [comment]
Ok, sehe ich ein :smile:
