### ISSUE TITLE
Regeln für Trier falsch?

### ISSUE THREAD

**Issue by miko007** [v-braun/corona-wiki#3]
Aktuell liefert das Wiki folgendes Ergebnis für Trier:

![image](https://user-images.githubusercontent.com/1271957/110322911-1d0ca000-8014-11eb-9006-f14c3bf47697.png)

Die 17. Coronaverordnung RLP vom 5. März 2021 sagt in §1, Absatz 1 allerdings:

> "Private Zusammenkünfte, die in der eigenen Wohnung oder anderen eigenen geschlossenen Räumlichkeiten stattfinden, sollen neben den Angehörigen des eigenen Hausstands auf Personen eines weiteren Hausstands, insgesamt auf höchstens fünf Personen, beschränkt werden, wobei Kinder beider Hausstände bis einschließlich 14 Jahre bei der Bestimmung der Personenanzahl außer Betracht bleiben. Als ein Hausstand zählen auch die und der nicht im gleichen Hausstand lebende Ehegattin und Ehegatte, Lebenspartnerin und Lebenspartner oder Lebensgefährtin und Lebensgefährte."

Für solche Fälle wäre es vermutlich hilfreich, wenn neben der aktuellen Lage auch die entsprechende Quelle verlinkt würde, die gerade als Grundlage für die Information dient, damit der Besucher das nachprüfen kann.

**Comment by v-braun** [comment]
Das ist n guter Punkt!
Ich habe in den Regelsätzen auch die Quelle (meist) gepflegt.

Ich muß nochmal gesondert die Coronaverordnung von RLP mal checken ob diese die Landesregeln wirklich übersteuern.
Sollte es so sein, so gibt es heute bereits die möglichkeit Regeln für Bundesländer anzulegen und diese werden dann statt den "Deutschlandweiten Regeln" angezeigt.

**Comment by miko007** [comment]
Die Quelle wurde ja jetzt verlinkt. In dem Absatz über die Inzidenzbestimmungen für private Treffen steht nochmals explizit:

> Entscheidend sind immer die Corona-Regeln der Bundesländer.

Also gilt hier §1, Absatz 1, [17. Corona-Bekämpfungverordnung RLP][1]

Das müsste man dann entsprechend nachpflegen, was allerdings eine heiden Arbeit hervorruft, wenn das für jedes Bundesland angepasst werden muss/man 16 Landesverordnungen durchlesen muss.

[1]: https://corona.rlp.de/fileadmin/rlp-stk/pdf-Dateien/Corona/17._CoBeLVO/17._CoBeLVO.pdf

**Comment by v-braun** [comment]
für ganz RLP angepasst

Danke dir vielmals für das Feedback!
