### ISSUE TITLE
Unterteilung von Karlsruhe in Stadt- und Landkreis

### ISSUE THREAD

**Issue by meyfa** [v-braun/corona-wiki#8]
Karlsruhe (Stadtkreis) und Karlsruhe (Landkreis) heißen beide einfach `Karlsruhe` und können nur anhand des Wappens unterschieden werden. Wäre es möglich dies zu unterteilen, wie z.B. bei Heilbronn?

**Comment by v-braun** [comment]
Danke für den Hinweis!
Ist erledigt, wird gerade deployed
